### ISSUE TITLE
Composer lock

### ISSUE THREAD

**Issue by ismaeljoseph** [muratbsts/stories#3]
Composer lock seems to have a conflict with composer.

Installation cannot be complete even with correct composer.lock.

Please test the installation.

**Comment by muratbsts** [comment]
Hi @ismaeljoseph it seems my mistake. I have a package named as `laravel-reactable` and I forgot local repository path in composer.json

**Comment by ismaeljoseph** [comment]
Thanks for paying attention to my comment.
